2025-02-12 13:54:09,626 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2025-02-12 13:54:09,628 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Configure stats pid to 3154526
2025-02-12 13:54:09,628 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Loading settings from /n/home00/jbook/.config/wandb/settings
2025-02-12 13:54:09,628 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Loading settings from /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/double_cascade_identification/scripts/wandb/settings
2025-02-12 13:54:09,628 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-02-12 13:54:09,629 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-02-12 13:54:09,629 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': '01_train_dynedge.py', 'program_abspath': '/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/double_cascade_identification/scripts/01_train_dynedge.py', 'program': '/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/double_cascade_identification/scripts/01_train_dynedge.py'}
2025-02-12 13:54:09,629 INFO    MainThread:3154526 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-02-12 13:54:09,629 INFO    MainThread:3154526 [wandb_init.py:_log_setup():533] Logging user logs to ./wandb/wandb/run-20250212_135409-pcyg6ehj/logs/debug.log
2025-02-12 13:54:09,630 INFO    MainThread:3154526 [wandb_init.py:_log_setup():534] Logging internal logs to ./wandb/wandb/run-20250212_135409-pcyg6ehj/logs/debug-internal.log
2025-02-12 13:54:09,630 INFO    MainThread:3154526 [wandb_init.py:init():619] calling init triggers
2025-02-12 13:54:09,630 INFO    MainThread:3154526 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {}
2025-02-12 13:54:09,630 INFO    MainThread:3154526 [wandb_init.py:init():669] starting backend
2025-02-12 13:54:09,630 INFO    MainThread:3154526 [wandb_init.py:init():673] sending inform_init request
2025-02-12 13:54:09,660 INFO    MainThread:3154526 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-12 13:54:09,660 INFO    MainThread:3154526 [wandb_init.py:init():686] backend started and connected
2025-02-12 13:54:09,712 INFO    MainThread:3154526 [wandb_init.py:init():781] updated telemetry
2025-02-12 13:54:09,714 INFO    MainThread:3154526 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2025-02-12 13:54:10,033 ERROR   MainThread:3154526 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-02-12 13:54:10,033 ERROR   MainThread:3154526 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/spack/var/spack/environments/graphnet/.spack-env/view/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "/n/holylfs05/LABS/arguelles_delgado_lab/Everyone/jbook/spack/var/spack/environments/graphnet/.spack-env/view/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-02-12 13:54:10,175 WARNING MsgRouterThr:3154526 [router.py:message_loop():75] message_loop has been closed
